# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CLK_MA35D1) += clk-ma35d1.o
obj-$(CONFIG_CLK_MA35D1) += clk-ma35d1-divider.o
obj-$(CONFIG_CLK_MA35D1) += clk-ma35d1-pll.o

obj-$(CONFIG_ARCH_NUC980) += clk-nuc980-ccf.o clk-nuc980-upll.o clk-nuc980-apll.o
